### ISSUE TITLE
关于任务计划的问题

### ISSUE THREAD

**Issue by nangongu** [overflow65537/MAA_Punish#9]
在通过GUI设置好后，可以在MFAWPF.exe中手动正常运行，但如果通过任务计划程序启动MFAWPF.exe并令其启动后自动运行脚本，就会在等待模拟器启动时间结束过后跳出链接失败的字样，日志记载如下：

2024-11-30 16:29:24.6481 INFO 正在连接至模拟器......
2024-11-30 16:29:24.8353 INFO 
2024-11-30 16:29:24.8353 INFO 正在初始化控制器
2024-11-30 16:29:26.7710 WARN 初始化控制器时发生错误！
2024-11-30 16:29:26.7835 ERROR MaaFramework.Binding.MaaJobStatusException: IMaaController failed to connect to the device. MaaJobStatus cannot be Failed.
System.Object[]
   at MaaFramework.Binding.MaaJobStatusExtensions.ThrowIfNot(MaaJobStatus current, MaaJobStatus correct, String message, Object[] args)
   at MaaFramework.Binding.MaaAdbController..ctor(String adbPath, String adbSerial, AdbScreencapMethods screencapMethods, AdbInputMethods inputMethods, String config, String agentPath, LinkOption link, CheckStatusOption check)
   at MFAWPF.Utils.MaaProcessor.InitializeController()
   at MFAWPF.Utils.MaaProcessor.InitializeMaaTasker()
2024-11-30 16:29:26.7835 WARN 初始化控制器时发生错误！
2024-11-30 16:29:26.7835 INFO 连接失败
2024-11-30 16:29:26.7835 INFO 正在停止......
2024-11-30 16:29:26.7835 INFO 已放弃本次任务

**Comment by overflow65537** [comment]
可能是有兼容问题
你先用maapicli自带的方法来使用计划任务吧
```
D:\Program Files\Netease\MuMu Player 12\shell\MuMuPlayer.exe -V 0
ping 127.0.0.1 -n 10 > nul
D:\MPA\MaaPiCli.exe -d
taskkill /f /im MuMuPlayer.exe
```
模拟器的```-V 0```代表运行多开模拟器的第一位模拟器,1则是第二个
如果模拟器启动速度太慢就将第二行 ```ping 127.0.0.1 -n 10 > nul```中的```10```调大
maapicli的 ```-d``` 参数可以让程序启动后直接按照保存的方案运行
保存为bat文件后点击就可以运行了

**Comment by nangongu** [comment]
1.在运行`E:\leidian\LDPlayer9\dnplayer.exe -V  0`命令后无法运行`ping 127.0.0.1 -n 40 > nul`命令，必须要在模拟器已经启动完成的情况下第二条命令才会执行读秒
2.在运行`E:\A Game butlers\MPA\MaaPiCli.exe -d`命令时，maapicli.exe会闪烁一下然后退出，无法正常进行任务，然后丝滑执行第四条`taskkill /f /im dnplayer.exe`命令光速把模拟器关掉，给我看乐了

以上两种情况单独执行相关命令都会出现，前者我也搞不明白为什么，后者会是因为maapicli.exe启动时必须要手动输入数字6才运行已保存方案的原因吗

**Comment by overflow65537** [comment]
1.雷电模拟器和mumu不一样,mumu启动的时候不会堵塞进程,所以需要`ping 127.0.0.1 -n 40 > nul`,看起来雷电并不需要这行命令

2.你设置了maapicli内的任务了吗,如果内部没有进行设置的话是会这样的.因为`-d`参数只会运行已经保存的任务

**Comment by nangongu** [comment]
1.这个问题其实不用解决，只需要我拆开两个计划任务就好了。
2.是的，我认为我应该已经完成了设置，并且我已经成功手动使用了maapicli运行了一次任务列表，我打开maapicli后的界面如下

Welcome to use Maa Project Interface CLI!
MaaFramework: v2.2.2

Version: v1.3.3

### Current configuration ###

Controller:

        安卓端
                E:/leidian/LDPlayer9/adb.exe
                emulator-5554

Resource:

        B 服

Tasks:

        - 进入游戏
        - 指挥局
        - 领取体力
        - 领取邮件
        - 购买碎片
        - 宿舍委托
        - 宿舍任务
        - 拟战场域
        - 守护者行动
        - 领取任务
        - 战令
        - 结束游戏

### Select action ###

        1. Switch controller
        2. Switch resource
        3. Add task
        4. Move task
        5. Delete task
        6. Run tasks
        7. Exit

Please input [1-7]:

**Comment by nangongu** [comment]
稍后我会使用Mumu模拟器再次尝试一下

**Comment by nangongu** [comment]
问题已解决

**Comment by overflow65537** [comment]
> 1.在运行`E:\leidian\LDPlayer9\dnplayer.exe -V  0`命令后无法运行`ping 127.0.0.1 -n 40 > nul`命令，必须要在模拟器已经启动完成的情况下第二条命令才会执行读秒
> 2.在运行`E:\A Game butlers\MPA\MaaPiCli.exe -d`命令时，maapicli.exe会闪烁一下然后退出，无法正常进行任务，然后丝滑执行第四条`taskkill /f /im dnplayer.exe`命令光速把模拟器关掉，给我看乐了
> 
> 以上两种情况单独执行相关命令都会出现，前者我也搞不明白为什么，后者会是因为maapicli.exe启动时必须要手动输入数字6才运行已保存方案的原因吗

这个问题呢

**Comment by nangongu** [comment]
问题2依然存在，不过我不从这个途径启动了所以对我没影响
